# Site settings
title: Kokipedia.com
author: Your Name
# author_avatar: https://gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=50
# email: alias@domain.tld
description: Jual alat perlengkapan dapur original dan bumbu masak halal.
baseurl: "" # optional
url: "https://kokipedia.com"
#twitter_username: foo_bar
#github_username: foo_bar
# github_repo: foo_bar/foo_bar.github.io
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
